[tools]
"water filter" = ""

[inputs]
"wide glass jar (≥100ml)" = ""
"10 g coarse-ground fruity coffee beans" = ""
"90-100 ml cold tap water (not distilled water)" = ""
"coffee cup (≥300ml)" = ""
"100-200 ml water or milk" = ""

[outputs]
"cold brew coffee"      = "300 ml"
"cold brew"             = "leftover"
"cold brew.longetivity" = "Store for 1 week in a fridge"

[steps]
1 = "Make cold brew"
1.1 = "Filter the tap water"
1.2 = "Add the ground coffee beans to the jar"
1.3 = "Pour the filtered water into the jar"
1.4 = "Mix and close the jar (or close and shake)"
1.5 = "Wait 12-24 hours"
2 = "Make cold brew coffee"
2.1 = "Pour 100 ml cold brew into a cup"
2.2 = "Pour 100-200 ml water or milk into the cup"

# TODO: https://morgandrinkscoffee.com/blogs/recipes-1/how-to-make-carmillas-kiss ?
