[inputs]
"mayonnaise"      = "120 ml"
"garlic powder"   = "1/2 tsp"
"lemon juice"     = "1/2 tsp"
"salt and pepper" = "to taste"

[outputs]
"garlic aioli" = "160 ml"
"garlic aioli.longetivity" = "4 weeks in a fridge (same as the mayonnaise)"

[steps]
1 = "Mix all ingredients in a bowl"
