tools = [
  "kettle",
  "milk pitcher ≥300ml",
  "hand frother",
  "low (and wide) 200ml coffee cup"
]

[inputs]
"espresso instant coffee" = "1 tsp"
"water"                   = "30 ml"
"whole (4%) milk"         = "150 ml"

[outputs]
"coffee with latte art" = "180 ml"

[steps]
1 = "Prepare an espresso shot."
1.1 = "Note: Using instant coffee is not ideal, but it should work if you use less water than recommended by the packaging."
1.2 = "Note: If you have a proper espresso machine, you will get a distinct "crema" layer of white-orange foam above the black coffee. However, this is not necessary for latte art."
# TODO: help
2 = "Fill the pitcher with milk up to the start of the spout. (halfway)"
3 = "Heat the pitcher on a stove up to 60°C (min 55°C, max 65°C) and gently stir."
4 = "Froth the milk"
4.1 = "Froth the milk just below the surface for 10s."
4.2 = "Froth under the milk, just above the bottom of the pitcher for ≥10s."
# -
5 = "Tap the pitcher against the counter and swirl. Repeat 3 times."
5.1 = "All remaining bubbles should be invisible."
6 = "Pour the 'steamed' milk from the pitcher into the coffee."
6.1 = "Pour slowly at first from a higher distance."
6.2 = "Then pour faster and closer to the surface."
