[tools]
"kettle" = ""
"milk pitcher" = "≥300ml"
"french press" = "≥240ml"
"ceramic mug"  = "≥200ml"

[inputs]
"(espresso) instant coffee with crema" = "1 tsp"
"water"           = "60 ml"
"whole (4%) milk" = "180 ml"
"300 ml mug"      = "1"

[outputs]
"coffee with latte art" = "294 ml"

[steps]
1 = "Heat your ingredients"
1.1 = "Microwave a cup of milk (in a ceramic mug) for 1 min (can be plant-based milk)"
1.2 = "Heat the water to 100°C"
2 = "Add air bubbles into the milk"
2.1 = "Pour the milk into a french press"
2.2 = "Pump up and down until the volume increases by 25-30%"
2.3 = "Then pump from the bottom to beneath the surface as much as you can"
3 = "Make an 'espresso shot'"
3.1 = "Put the instant coffee into a new mug"
3.2 = "(You can add sugar here if you want)"
3.3 = "Pour the hot water along the side of the mug"
4 = "Remove big bubbles from the milk"
4.1 = "Pour the frothed milk back into the mug"
4.2 = "Then pour it from the mug into the pitcher"
4.3 = "(You can also tap the pitcher against the counter and swirl)"
5 = "Pour the milk into the coffee"
5.1 = "https://www.youtube.com/watch?v=-8oguwS87kI"
